# -*- coding: utf-8 -*-
"""ATIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-Jz2F9OJnd69tIepKKtsmq30UXGG7Q1
"""

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/ATIS.zip"

import zipfile
import os

extract_path = "/content/atis_data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import os

for root, dirs, files in os.walk(extract_path):
    for file in files:
        print(os.path.join(root, file))

import pandas as pd

train_df = pd.read_csv("/content/atis_data/atis_intents_train.csv")
test_df  = pd.read_csv("/content/atis_data/atis_intents_test.csv")
full_df  = pd.read_csv("/content/atis_data/atis_intents.csv")

train_df = pd.read_csv(
    "/content/atis_data/atis_intents_train.csv",
    header=None,
    names=["label", "text"]
)

test_df = pd.read_csv(
    "/content/atis_data/atis_intents_test.csv",
    header=None,
    names=["label", "text"]
)

print(train_df.head())
print(train_df['label'].value_counts().head())
print("no of intents:", train_df['label'].nunique())



from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(train_df['label'])
y_test  = le.transform(test_df['label'])

def clean_text(text):
    text = text.lower()                               # lowercase
    text = re.sub(r'\d+', '', text)                   # remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))  # remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()          # remove extra spaces
    return text

import string
import re
train_df['text_clean'] = train_df['text'].apply(clean_text)
test_df['text_clean']  = test_df['text'].apply(clean_text)

print(train_df[['text', 'text_clean']].head())

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_words = 10000
max_len   = 30

tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(train_df['text_clean'])

X_train_seq = tokenizer.texts_to_sequences(train_df['text_clean'])
X_test_seq  = tokenizer.texts_to_sequences(test_df['text_clean'])

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len, padding='post')
X_test_pad  = pad_sequences(X_test_seq,  maxlen=max_len, padding='post')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

num_classes = len(le.classes_)

model = Sequential([
    Embedding(max_words, 128, input_length=max_len),
    LSTM(128, return_sequences=False),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stop = EarlyStopping(
    monitor='val_accuracy',
    patience=3,
    mode='max',
    restore_best_weights=True
)

history = model.fit(
    X_train_pad,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stop]
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='train_accuracy')
plt.plot(history.history['val_accuracy'], label='val_accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

loss, acc = model.evaluate(X_test_pad, y_test)
print("Test Accuracy:", acc)

from sklearn.metrics import classification_report

y_pred = model.predict(X_test_pad).argmax(axis=1)
print(classification_report(y_test, y_pred, target_names=le.classes_))

"""Deployment"""

model.save("intent_model.keras")

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)



!ngrok authtoken 39QVycWvcpdi93o2HsUR51zh3ox_2XxqPaqyeycTozq1Uapav

!pip install flask pyngrok tensorflow requests -q

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
from flask import Flask, request, jsonify
from pyngrok import ngrok
import numpy as np
import pickle
import re
import string
from threading import Thread
import time
import requests


model = load_model("intent_model.keras")


with open("tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)
with open("label_encoder.pkl", "rb") as f:
    le = pickle.load(f)

max_len = 30



def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def predict_intent(text):
    text_clean = clean_text(text)
    seq = tokenizer.texts_to_sequences([text_clean])
    padded = pad_sequences(seq, maxlen=max_len, padding='post')
    pred = model.predict(padded)
    class_idx = np.argmax(pred, axis=1)[0]
    class_label = le.inverse_transform([class_idx])[0]
    confidence = float(np.max(pred))
    return class_label, confidence


app = Flask(__name__)

@app.route("/")
def home():
    return "Flask API is running!"

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "No text provided"}), 400
    class_label, confidence = predict_intent(text)
    return jsonify({"intent": class_label, "confidence": confidence})


tunnel = ngrok.connect(5000)
public_url = tunnel.public_url
print(" * API URL (ngrok):", public_url)


def run_flask():
    app.run(host="0.0.0.0", port=5000)

thread = Thread(target=run_flask)
thread.start()

time.sleep(3)


def test_text(text):
    url = f"{public_url}/predict"
    data = {"text": text}
    response = requests.post(url, json=data)
    return response.json()

# example for testing
result = test_text("show me the second class fares from boston to denver")
print(result)

